share/site/duckduckgo/head_js.tx
share/site/duckduckgo/settings.tx

Making publisher page instantiation consistent so it happens at page load instead of waiting for DOMReady.
cc @sdougbrown @nilnilnil

Don't wait for DOMReady to instantiate the page instance anymore

---

dist.ini

`[Repository]` is clashing with another Dzil Plugin, (I think `[GitHubMeta]`), trying to set the `web` property of the generated META.yml
`index_base_url` should be updated to match newest PromptIfStale requirements
//cc @nilnilnil @sdougbrown @jbarrett

remove [Repository], fix [PromptIfStale] option

---

share/site/duckduckgo/api.tx

I was reading through the DuckDuckGo API site and noticed that the "supporting library integrations" section didn't have any OCaml libraries. So, I decided to [write one and I put it on Github](https://github.com/mwhittaker/duckduckgo-ocaml)! I was hoping it could be added to the "supporting library integrations" section :D

duckduckgo-ocaml

---

share/site/duckduckgo/about.tx

One misplaced quote mark mangles the whole page in IE8. :)
cc @nilnilnil

(about) fix malformed quote location on team page

---

share/site/duckduckgo/header.tx
share/site/duckduckgo/search_form_hero.tx
share/site/duckduckgo/search_form_homepage.tx

Our JS search forms now require an 'overlay' element to give rich feedback on your search query when the field is not in focus.  This adds those elements.
cc @bsstoner @nilnilnil

Search Form - 'Overlay' Element

---

share/site/duckduckgo/styleguide.tx

Classnames changed internally to be more consistent with the template names and prevent confusion - this just updates the page to use the correct classes. :)
cc @bsstoner

Styleguide - Renaming 'Text' Content Layouts

---

share/site/duckduckgo/base.tx

We changed from `:before` pseudo element to actual div element so it would work in IE8, but the static pages weren't also updated.
@nilnilnil 
cc @sdougbrown

Add div for top red border on static sites

---

share/site/duckduckgo/base.tx

We don't want the fixed-position header border to appear on pages where we have a 'hero' section.  This just conditionally includes it now.
cc @bsstoner

Conditional Header Border

---

share/site/duckduckgo/search_box.tx

The search form iframe doesn't work in many browsers unless `https` is explicitly used - this just updates the page accordingly so that future users don't run into any issues. :)
to @yegg

Search Box HTTPS

---

lib/DDG/Publisher/Site/Duckduckgo/Root.pm
share/site/duckduckgo/meta/base.tx

We need to include the new serp stylesheet on the styleguide for everything to work correctly. :smile: 
Requires an internal PR to init `DDG_DYNAMIC_CSS_3_FILE` on deploy.

Styleguide - SERP Styles

---

share/site/duckduckgo/spread.tx

We're going to be more selective when we display this section, so we're hiding it by default.  If someone is clever enough to find it in open source or in the page source then we probably want to give them a t-shirt anyway. :smile: 
Requires an internal PR for the javascript to display it again.
to @zekiel 
cc @bsstoner @andrey-p

Spread Page - Hide T-Shirt Section

---

share/site/duckduckhack/doc.tx

@moollaza @DavidMascio 
Well, this is where the breadcrumb lives. Took duckduckhack.com out of the second level, made both links point to duck.co.

Fix for DDH docs breadcrumb, make it hierarchical, nix dukgo.com

---

share/site/duckduckgo/_logo_homepage.tx
share/site/duckduckgo/header.tx

Requires an internal PR for the tooltip styling.
I also removed an old special logo that we just had commented out.  I don't really think we want that showing as a comment in production anymore.
to @yegg

Homepage Logo Tooltip

---

share/site/duckduckgo/privacy.tx

Update from a dead redirect to the correct Help page article.
to @bsstoner 
cc @yegg

(Privacy Policy Page) - Fix Tor Link

---

lib/DDG/Publisher/Site/Duckduckhack/Root.pm

This git clone is failing with our new github.com changes. Using https we can avoid using our github.com keys just to checkout this repo.
cc: @malbin @marcantonio

use the https URL for git clone

---

lib/DDG/Publisher/Site/Duckduckhack/Root.pm

So the reason this one site is so sluggish is it ties up starman server instances while it clones and builds the docs repo.
With this change you can set an environment variable to skip all the docs operations, so instead of:
```
duckpan publisher
```
You would run:
```
DDH_SKIP_DOCS_BUILD=1 duckpan publisher
```
You would, of course, leave this out if you need to build and evaluate docs :smile:
The number to pay attention to is '/' - generation goes from 10 seconds to 1. Still not quite as zippy as the other sites in publisher but better if you need a fast feedback loop.
After the first request, the static files (which you can see taking around 25 seconds to serve in the before shot) are served almost instantly. I just left these in to show the improvement in initial request time too. …

Speeding up duckduckhack.com development

---

lib/DDG/Publisher/Site/Duckduckhack/Root.pm

I messed this up in #214 - this hash is needed to actually build pages.
After this is merged, we can then pull in @preemeijer's fix in #213

Restoring DDH pages hash with IA / Contributor info

---

lib/DDG/Publisher/Site/Duckduckhack/Root.pm

Hello,
Came across a link that isn't working anymore.
The original github link for the Regex cheat sheet gives a user an 404 message.
Greetings, Paul

fixed broken link to regex cheat sheet github link

---

share/site/duckduckgo/header.tx
share/site/duckduckgo/search_form_hero.tx
share/site/duckduckgo/search_form_homepage.tx

We're not using the overlay anymore, it's unnecessary to have the element on the page.
@andrey-p

Remove site overlay element

---

share/site/duckduckhack/index_content.tx

@russellholt 
We need to link to the community section from Duck.co. 
It would be helpful to be able to link to any section in the future as well.
Ids are as follows, beginning after the hero screenshot carousel:
- `power-of-ias`
- `get-involved`
- `get-help`
- `join-community`<--- this is the one @jagtalon will want to link to from Duck.co
- `plaudits` 
- `ia-suggestions`

Add ids to major sections of DDH

---

share/site/duckduckgo/api.tx

I think this is an unnecessary distraction. We don't have a similar message in most (all?) other English pages so will probably be OK without it here.

Remove "untranslated" warning

---

lib/DDG/Publisher/Site/Duckduckhack/Root.pm
share/site/duckduckhack/index_content.tx

Immediate changes to duckduckhack that will improve the onboarding process for the programming mission by funneling users to a single point, removing distractions:
- Link "Get Started" to the Programming Mission Overview 
- Update carousel text
- Hide power of IAs and develop/fix sections for now because both links present distractions from the Programming Mission
- Remove Programming Mission banner
- Change the image to the regex cheat sheet to highlight programming IAs
cc: @zac @russellholt @abeyang

Programming Mission Onboarding Updates

---

share/site/duckduckgo/search_box.tx

The original site has been taken offline so linking to Wayback Machine's archive instead.
(and my editor removes whitespace automatically)
Originally [reported on Twitter](https://twitter.com/deepdeviant/status/768523280487686145)

Fixed broken link

---

share/site/duckduckgo/about.tx

Following suggestions by @andrey-p and @chrismorast in https://app.asana.com/0/inbox/42485752355997/248995145166035/249079438970887

Added social media links to About page

---

lib/DDG/Publisher/Site/Duckduckgo/Root.pm

Adds 2017 start of year updates to the timeline on the about page.

add 2017 start of year updates to about timeline

---

share/site/duckduckgo/about.tx

Since DuckDuckHack is winding down, we're removing the hack section in the about page.

About Page: Remove the hack section

---

lib/DDG/Publisher/Site/Duckduckgo/Root.pm

The Fast Company link is broken so this fixes it.
The other two links are changed to HTTPS.

Fixed links in About page

---

lib/DDG/Publisher/Site/Duckduckgo/Root.pm
share/site/duckduckgo/about.tx
share/site/duckduckgo/press.tx

- Better BEM naming for fact card
- Removed `flex-row`, flex layout handled internally via CSS
- Updated text for 'Privacy, Simplified' card on About page
- Also updated icon
- Corrected 10M icon in About timeline

Press + About Page Mobile UI Tweaks; About page text update

---

lib/DDG/Publisher/Site/Duckduckgo/Root.pm
share/site/duckduckgo/donations.tx

- Removes CrowdRise campaign CTA from hero
- Adds 2018 CrowdRise participants to list
**Note:** Requires internal CSS changes

Add in 2018 donations, remove CrowdRise CTA

---

lib/DDG/Publisher/Site/Duckduckgo/Software.pm
share/site/duckduckgo/product_page.tx

- Updates version number
- Removes unused 'Title' property for hash
- Added 'Platform' to name so it's always presented with 'PortableApps.com'

Update Portable Apps Platform to v15.0.2

---

share/site/duckduckgo/newbang.tx

I think this page was previously lacking some of our shared styles. We rejigged the static styles recently so they were added.
The subcategory dropdown was using `.invisible` as a class name, but didn't remove it. `.invisible` now has `visibility: hidden !important` so it trumps the styles changed via JS.
1. Get this running on your machine
2. Go to https://konrad.duckduckgo.com/newbang
3. Scroll down to where it says "bang category" - the subcategory field should be hidden
4. Pick a bang category - the subcategory field should appear

Use classnames to show/hide bang form subcategory field

---

lib/DDG/Publisher/Site/Duckduckgo/Root.pm
share/core/footer_copyright.tx
share/site/duckduckgo/base.tx

- Updated default copyright footer text to `DuckDuckGo. Privacy, simplifed` -- which we've used on all recent new/updated pages.
- Created a `%page_defaults` hash to DRY up standard static page definitions in `Root.pm`
- Deploy changes
- Check the following. Pages that have a nav footer should now have the about footer. Pages without footers should remain the same. Pages with copyright footer should all have the same text.
- https://jag.duckduckgo.com/about -- unchanged
- https://jag.duckduckgo.com/api -- unchanged
- https://jag.duckduckgo.com/app -- unchanged
- https://jag.duckduckgo.com/bang -- about footer + new copyright text
- https://jag.duckduckgo.com/donations -- new copyright text
- https://jag.duckduckgo.com/duckduckbot -- unchanged
- https://jag.duckduckgo.com/duckduckpreview …

Standardize copyright text; Simplify static page defaults; 

---

share/site/duckduckgo/feedback.tx

This change changes the bug report link to just handle security reports through h1

Redirect security reports to h1

---

share/site/duckduckgo/bang.tx

Tweaks the phrasing on the bang page a bit. I also rejigged the classes slightly, see internal PR.
- the updated copy should be there
- the interaction should still work (e.g. pressing on `!w filter bubble` should show the search bar with the bang prefilled)

Change phrasing on bang page

---

share/site/duckduckgo/params.tx

This option was removed on DDG, as organic results are simply outlined (no background color on hover).
Pull the latest static code and go to to /params.

Remove docs for unused 'ky' setting.

---

lib/DDG/Publisher/Site/Duckduckgo/Root.pm

Change it to a more accurate date on when we started to implement anonymity.

Duckduckgo/Root.pm: Change anonymous tracking timeline date.

---

share/site/duckduckgo/about.tx

Replaces the team map with a team photo.
Asana: https://app.asana.com/0/72649045549333/1109764254025247
cc @jagtalon @moollaza 
You'll need to checkout the branch with core changes here: https://dub.duckduckgo.com/duckduckgo/ddg/pull/15043
1. Go to yourinstance.com/about
2. Scroll down to "Our Global Team"
3. Verify that the team map is not showing
4. Verify that the team photo is showing and is full-screen
5. Verify that "We're hiring" link is displayed as a blue button
6. Test various breakpoints and make sure that it looks OK

About page: replace team map with photo

---

share/site/duckduckgo/about.tx

Replaces About page team photo with a screenshot of the team map.
1. Pull https://dub.duckduckgo.com/duckduckgo/ddg/pull/15081
2. Run `rex deploy:static_dev
3. Go to instance.duckduckgo.com/about and verify that the team map png is used in the html (it may not be immediately obvious since the css background image is displayed on the page, so you'll need to inspect the html to verify this).

Replace About page team photo with map screenshot

---

share/site/duckduckgo/press.tx

Add open@duckduckgo.com to the press page for non-press inquiries.
Go to https://duckduckgo.com/press, the text above the press@duckduckgo.com button should be changed, and a new email open@duckduckgo.com should be added below.

Add email to press page for non-press inquiries.

---

share/core/footer.tx
share/core/footer_nav.tx
share/site/duckduckgo/api.tx
share/site/duckduckgo/feedback.tx
share/site/duckduckgo/params.tx
share/site/duckduckgo/privacy.tx
share/site/duckduckgo/search_box.tx

- Updating old help links
- Removing duck.co links from feedback, linking directly to pages where feasible

Update help and feedback links

---

share/site/duckduckgo/meta/base.tx

Missed this when favicon changes were released recently.

Remove 24 and 64 from list of favicon sizes

---

share/site/duckduckgo/press.tx

Adds a button allowing quick scroll to "Press Materials" section.
Relies on internal CSS changes.

Add CTA + anchor for Press Materials
