duckduckgo/duckduckgo-publisher

- share/site/duckduckgo/about.tx
//cc @sdougbrown  can you please merge if it looks ok? Otherwise, I will make any necessary updates-don't want to distract.
> added newsletter anchor

- share/site/duckduckhack/inc/head.tx
Missing title reported by @MrChrisW - thanks.
@sdougbrown @chrismorast Would you like me to change the text?
> Add title tag to DuckDuckHack header.

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/about.tx
- share/site/duckduckgo/tour.tx
Two new members and a hiring callout.
Requires an internal PR for the new images.
> About Page - Team Update

- share/site/duckduckgo/base.tx
- share/site/duckduckgo/meta/goodies.tx
minor last remaining traces of the old goodies page
> remove some old goodies page tx

- share/site/duckduckgo/search_box.tx
> removed old ref. to gabe's blog

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/styleguide.tx
Requires an internal PR.
cc @bsstoner
> Styleguide - Content Layout Updates

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/styleguide.tx
Making some internal changes to color names to make things easier for everyone. :)
Requires an internal PR.
cc @chrismorast @bsstoner
> Styleguide - Color Updates

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Photo added via an internal PR.
to @chrismorast
> Add Adam to the About Page team section

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Using a couple new icons for the timeline.
cc @yegg
> New About Page Timeline Icons

- share/site/duckduckgo/spread.tx
Just updating the wording in the hero section.
to @yegg
> Spread Page Hero Text Change

- share/site/duckduckgo/tour.tx
//cc @sdougbrown  can you please review and let me know if I botched it? :)
> added DDH link to IA section of Tour

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/core/footer_nav.tx
- share/site/duckduckgo/about.tx
Adjusting the content and callouts.
to @yegg
> About Page - Text Revisions

- share/site/duckduckgo/spread.tx
Adjusting the wording for the spread page.
to @yegg
> Spread Page - T-Shirt CTA Updates

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
> Styleguide - Grey Shade Updates

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Tired of the youtube link :)
to: @sdougbrown
> update jaryd's URL

- share/site/duckduckgo/popout.tx
- share/site/duckduckgo/popover.tx
- share/site/duckduckgo/styleguide.tx
Some work has been done to make these modals easier to use and more accessible, so they're being put back on the styleguide page.
Requires an internal PR for styling and functionality.
to @bsstoner
> Styleguide - Popouts & Popovers

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Updating the names of some current icons to make them easier to remember and use, removing a couple of depreciated icons, and adding a few new ones.
Requires an internal PR for the new icons and the name changes.
> Styleguide - Icon Listing Update

- share/site/duckduckgo/head_js.tx
This will require an internal PR to actually use this data.
cc @jbarrett @bsstoner
> Pass Locale to JS

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Adding a few more icons to the internal icon font - updating the styleguide accordingly.
Obviously requires an internal PR. :)
> Styleguide - More Icons

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/app.tx
- share/site/duckduckgo/meta/app.tx
This is part of an internal PR.
> WIP: New app page

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/bang.tx
- share/site/duckduckgo/head_js.tx
> New bangs page

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
I honestly forgot that Prakash had a surname :)
to @bsstoner
> Team Member Surname

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
It's probably not the same as Adam's.  Oops. :)
> Fix Jeffrey's personal site link

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/about.tx
- share/site/duckduckgo/app.tx
Goes hand in hand with an internal PR.
@sdougbrown 
cc @chrismorast @thm @bsstoner
> App page improvements

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Updating the timeline with this milestone.
to @yegg 
cc @chrismorast
> About Page - 10,000,000

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
I made a mistake with a double http header.
> Fix Jeffrey's personal site link again

- share/site/duckduckgo/about.tx
> Added styling hook for title link in Get Involved section in About

- .travis.yml
This reverts commit 1a8de92cbd83e6c1ab74a99d2568802375631ed9.
> Revert "(travis) quote numeric strings"

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Adds some new/missing icons to the styleguide page.
to @bsstoner
> Icon List Update

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
@sdougbrown are these in any order?
> add news icon to styleguide

- share/site/duckduckgo/header.tx
> Remove tooltip from header

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Adding arrows, re-sorting to alphabetical to clean up this mess I made. :)
to @bsstoner
> Styleguide - Icons Update

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/core/footer_nav.tx
Part of an internal PR.
@bsstoner 
cc @sdougbrown
> Bang page improvements

- share/site/duckduckgo/about.tx
> Remove team block

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/app.tx
> Simplified screenshot naming in /app

- share/site/duckduckgo/about.tx
This is linked to an internal PR (css related change to go with it).
> text tweaks for height alignment

- share/site/donttrackus/head.tx
Following on from https://github.com/duckduckgo/p5-app-duckpan/pull/285
Belt, meet braces.
> Add content-type meta tag for donttrackus

- share/core/head_js.tx
- share/site/duckduckgo/head_js.tx
> Get static page JS out of base JS

- share/site/duckduckgo/spread.tx
Cc: @bsstoner @chrismorast @zekiel
> Remove T shirt link from /spread

- share/site/duckduckgo/popout.tx
- share/site/duckduckgo/popover.tx
- share/site/duckduckgo/styleguide.tx
Fixing updated styles / functionality for modals. Internal.
cc @bsstoner @bbraithwaite
> Fix modals

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/yahoo_static.tx
Holding page for DDG owned yhs sub-domain.
> add basic page and text

- share/site/duckduckhack/index_content.tx
@russellholt are there any other changes we meant to make to the urls in publisher?
> Removed errant '/' from beta server url

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
> Add copyright notice to bang page

- share/site/duckduckgo/search_box.tx
> Update link at bottom of /search_box

- share/site/duckduckgo/bang.tx
- share/site/duckduckgo/tour.tx
- share/site/duckduckhack/index_content.tx
Goes with internal PR.
@andrey-p
> Load retina hero image on tour page

- share/site/duckduckgo/meta/base.tx
Goes with internal PR, to update the version number on the homepage.
@bbraithwaite
> Add version number to opensearch filename

- share/site/duckduckgo/meta/base.tx
> Update version number for opensearch.xml file

- share/site/duckduckgo/params.tx
> Added kaj to params

- share/site/duckduckgo/meta/base.tx
> opensearch_v3.xml

- share/site/duckduckhack/index_content.tx
@jagtalon can you review?
I've applied a new class in this PR to display an icon rather than the old date.
> Replace "Jan 30" on duckduckhack.com

- share/site/duckduckgo/params.tx
> Added info about kam parameter

- share/site/duckduckgo/meta/base.tx
> Updated opensearch.xml version

- share/site/duckduckgo/meta/base.tx
> Bump opensearch xml to v5

- share/site/duckduckgo/meta/base.tx
> bump opensearch to v6

- share/site/duckduckgo/meta/base.tx
> Increment opensearch.xml to v7

- share/site/duckduckgo/meta/base.tx
> bump opensearch version to v8

- share/site/duckduckhack/index_content.tx
Updated the Slack invitation link to Daniel's new app.
> Updated Slack Link

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/meta/base.tx
- share/site/duckduckgo/switch1.tx
- share/site/duckduckgo/switch2.tx
- share/site/duckduckgo/switch3.tx
- share/site/duckduckgo/switch4.tx
- share/site/duckduckgo/switch5.tx
- share/site/duckduckgo/switch6.tx
This goes with an internal PR
cc @andrey-p
> Add /switch landing pages

- share/site/duckduckgo/meta/base.tx
> opensearch v9

- share/site/duckduckgo/meta/base.tx
> Increment opensearch to v10

- share/site/duckduckgo/meta/base.tx
> Bump opensearch to v11

- share/site/duckduckgo/meta/base.tx
> Opensearch v12

- share/site/duckduckgo/meta/base.tx
> opensearch v13

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/install_firefox.tx
> Static page for FF Install Instructions

- share/site/duckduckgo/meta/base.tx
> Bump to opensearch_v14

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/meta/base.tx
> Increment to opensearch_v16

- share/site/duckduckgo/styleguide.tx
Fix a minor typo in the DDG Style Guide.
> Fix minor typo in the Style Guide

- .travis.yml
- dist.ini
Noticed it was failing in the most recent Pull Request
/cc @zachthompson
> Cleanup dist.ini and travis.yml

- share/site/duckduckgo/styleguide.tx
Noticed this when reading through.
> Correct typo

- share/site/donttrackus/index.tx
> Change to double tick

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/meta/base.tx
> Update to opensearch v18

- share/site/duckduckgo/install_chrome.tx
- share/site/duckduckgo/install_firefox.tx
Goes with an internal PR
cc @andrey-p
> Updates to the chrome atb install page

- share/site/duckduckgo/install_chrome.tx
- share/site/duckduckgo/install_firefox.tx
More minor tweaks to the full page instruction styles.
> Full page instructions tweaks

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/install_chrome.tx
- share/site/duckduckgo/install_firefox.tx
- share/site/duckduckgo/meta/base.tx
Requires internal PR
cc @nilnilnil @bbraithwaite @andrey-p
> Dynamic opensearch.xml

- share/site/duckduckgo/spread.tx
Shouldn't be merged until complementary internal PR is merged that creates the easter eggs.
> Add easter egg message to spread page.

- share/site/duckduckhack/index_content.tx
Added a banner to link to the `Improve Programming Results` project in the forum. 
cc: @russellholt @zekiel
> Programming Mission Banner

- share/site/duckduckgo/install.tx
@bsstoner 
Just noticed your comment. Here's the tag :)
> Adding closing tag

- share/site/duckduckgo/spread.tx
> Fix spread on mobile

- share/site/duckduckgo/newbang.tx
Most (all?) users don't realise this form can be used for updating or fixing broken bangs. This change should help.
> Bang form: Add note for updating existing bangs

- share/site/duckduckgo/footer_homepage.tx
> ip -> DDG.device.isIDevice

- share/site/duckduckgo/spread.tx
> Adding class to twitter button

- share/site/duckduckgo/footer_homepage.tx
> remove nuo

- share/site/duckduckgo/feedback.tx
Looks like my editor removed a load of whitespace too.
> Removed links to old forum

- share/site/duckduckgo/about.tx
Goes with an internal PR.
@ak2344 @bbraithwaite
> Add atb buttons to about page

- share/site/duckduckgo/tour.tx
> Add atb to the tour page

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/privacy.tx
> Add atb to privacy page

- share/site/duckduckgo/api.tx
@moollaza can you confirm these are right?
> Update cpan links on /api

- share/site/duckduckgo/privacy.tx
> Remove links to microsites from /privacy page

- share/site/duckduckgo/base.tx
This reverts commit 2da5faa6e16ec1c8ee455ae47bf1a675ccbbabc3.
> Revert "share/site/duckduckgo/base.tx: Add .beta class"

- share/site/duckduckgo/meta/base.tx
For an internal PR.
cc @bsstoner
> Add manifest.json to static pages

- share/site/duckduckgo/index.tx
> Make noscript homepage tagline same as JS homepage

- share/site/duckduckgo/api.tx
The new message at the top will hopefully reduce some confusion for developers looking for a full results API.
Also, my editor has removed lots of trailing spaces.
> Updates to API static page

- share/site/duckduckgo/meta/about.tx
- share/site/duckduckgo/meta/api.tx
- share/site/duckduckgo/meta/app.tx
- share/site/duckduckgo/meta/bang.tx
- share/site/duckduckgo/meta/base.tx
- share/site/duckduckgo/meta/duckduckbot.tx
- share/site/duckduckgo/meta/duckduckpreview.tx
- share/site/duckduckgo/meta/feedback.tx
- share/site/duckduckgo/meta/index.tx
- share/site/duckduckgo/meta/newbang.tx
- share/site/duckduckgo/meta/params.tx
- share/site/duckduckgo/meta/privacy.tx
- share/site/duckduckgo/meta/search_box.tx
- share/site/duckduckgo/meta/settings.tx
- share/site/duckduckgo/meta/spread.tx
- share/site/duckduckgo/meta/styleguide.tx
- share/site/duckduckgo/meta/title.tx
- share/site/duckduckgo/meta/tour.tx
* Removed unnecessary/deprecated metadata tags
* Removed video player tags from About page (out of date)
* Added missing metadata tags for Twitter and Facebook
Note: All descriptions reviewed by Gabriel.
Fixes #292
> Added metadata for social media snippets

- share/core/footer_nav.tx
Link to an actual live link ;)
> Change job links

- share/core/footer_nav.tx
Also changed Reddit link to HTTPS.
> Updated meetup.com URL

- share/site/duckduckgo/feedback.tx
> Fix feedback page

- share/site/duckduckgo/params.tx
> Add three-tier safe search to params page

- share/site/duckduckgo/newbang.tx
Marking this as WIP - it depends on [DaxMailer](https://github.com/duckduckgo/DaxMailer) going live.
Thanks!
> New POST endpoint for bang submission

- share/site/duckduckgo/api.tx
This is to reduce confusion and incoming questions about the API.
Also added link to a new R library to this PR to avoid merge conflicts.
> API page: Result syndication clarification & new R libary

- share/site/duckduckgo/about.tx
This reflects the text we have on the [Spread page](https://duckduckgo.com/spread).
> About page: Added disclaimer to newsletter signup

- share/site/duckduckgo/about.tx
Added a link to example content.
> Newsletter: Updated disclaimer

- share/site/duckduckgo/meta/spread.tx
- share/site/duckduckgo/spread.tx
Reverts duckduckgo/duckduckgo-publisher#309
> Revert "Spread Page! 🌚"

- share/core/footer_nav.tx
Change duck.co to spreadprivacy.com
> Change blog link in about page and bangs

- share/site/duckduckgo/tour.tx
No reason to link there now that DDH is in maintenance mode.
Live on https://moollaza.duckduckgo.com/tour
> Tour Page: Remove mention of DDH

- share/site/duckduckgo/footer_homepage.tx
@jbarrett You mind taking this?
> New error message for too many search terms

- share/site/duckduckgo/footer_homepage.tx
Following on from #331 this will apply a locale call to the new error text.
> Wrap error text in locale call

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/donations.tx
Update 2017 Freedom of the Press amount + yearly and overall totals
> Update Donations Totals

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
> Donations: Typo fix Patent -> Patient

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/about.tx
- share/site/duckduckgo/press.tx
- Updated icon names
- added no-js__hide in a few places to keep the page from looking bad with JS disabled.
**Depends on Internal PR for updated image assets**
> About & Press Page Refinements

- share/site/duckduckgo/about.tx
Updated UI for newsletter section:
- New button and form input styles
- Updated element widths
**Depends on internal CSS changes**
> About Page: Update Newsletter UI

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
> Root.pm: Activate footer for App Page

- share/core/footer_about.tx
- share/site/duckduckgo/about.tx
- share/site/duckduckgo/press.tx
- Remove `flex-row` from blog card container (added by View now)
- Fix title/sentence casing
- Add title to Press page message (bottom section)
- Add new js classes to links
> More updates to About/Privacy Pages

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Adds our recent App & Extension launch to the About page timeline
> About Timeline: Add 2018 Extension + App Launch

- share/site/duckduckgo/meta/index.tx
Added 'Search Engine' to our title text
> Update homepage title tag text

- share/core/header.tx
- share/site/duckduckgo/header.tx
- share/site/duckduckgo/header_homepage.tx
Creating a new container, `js-header-aside`, for the SideMenu and HeaderLinks that will be present on SERP + Homepage (and possibly Static pages)
**This PR requires internal changes. Do Not Merge.**
> Consolidate SideMenu + HeaderLinks into new js-header-aside container

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
Will add this back later by reverting this commit.
> Root.pm: Remove 2018 donations *for now*

- share/site/duckduckgo/product_page.tx
Simplifying DDG CTA by only showing one size for all screen sizes.
> PortableApps: Remove extra ad sizes; Rename to CTA

- lib/DDG/Publisher/Site/Duckduckgo/Software.pm
> Update Q-Dir to v7.01

- lib/DDG/Publisher/Site/Duckduckgo/Software.pm
> Software Pages: Update Firefox and PortableApps Platform

- share/site/duckduckgo/duckduckbot.tx
Remove old and add new crawler IPs
> Update duckduckbot ips

- share/site/duckduckgo/meta/base.tx
Use new, smaller`home.css` for homepage instead of `static.css`
> Load home.css for homepage only

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/base.tx
- share/site/duckduckgo/header_flex.tx
- share/site/duckduckgo/software.tx
> PA: Create new standalone download page for /software url

- lib/DDG/Publisher/Site/Duckduckgo/Software.pm
> Update to FF 61

- share/site/duckduckgo/about.tx
> about.tx: Change copy for the newsletter CTA 👏🏽

- share/site/duckduckgo/about.tx
- share/site/duckduckgo/press.tx
> Change employee number from 45 to 53 🙌🏽

- share/site/duckduckgo/about.tx
- share/site/duckduckgo/press.tx
Updated the donation amount in the About and Press pages to include the 2018 campaign.
> Updated donation totals

- share/site/duckduckgo/about.tx
- share/site/duckduckgo/press.tx
> Bump search numbers from 16B to 21B.

- share/site/duckduckgo/params.tx
> add kav settings to params page

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
> Fixed number of donation recipients

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
> Pass bang version to newbang page

- share/core/footer_copyright.tx
> footer_copyright.tx: Add address

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/core/footer_copyright.tx
Remove address everywhere except for the About Page.
> Root.pm: Add a property which toggles the footer to show our address.

- share/site/duckduckgo/about.tx
- share/site/duckduckgo/press.tx
Updated the fast facts on the Press and About pages.
> Updated Fast Facts

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/app_info.tx
- share/site/duckduckgo/meta/app_info.tx
Duplicate of exisiting /app page, but without the footer.
**Note:**  This depends on internal CSS changes
/cc @brindy
> Create new app_info page

- share/site/duckduckgo/meta/about.tx
Removes JS that is no longer needed on the page
> Remove map JS from About page

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/chrome_newtab.tx
- share/site/duckduckgo/meta/chrome_newtab.tx
> Chrome New Tab Page

- share/site/duckduckgo/about.tx
- share/site/duckduckgo/press.tx
Updated stats for the About page and Press page.
> Updated company stats

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/chrome_newtab.tx
Add tag line to the new tab page
> Add tag line to the new tab page

- lib/DDG/Publisher/Site/Duckduckgo/Root.pm
- share/site/duckduckgo/about.tx
Switch sections around so that we can show people what DuckDuckGo is about (heh) quickly.
> About page structural changes
